### ISSUE TITLE
Bug when moving adjacent selections down

### ISSUE THREAD

**Issue by evanrelf** [alexherbo2/move-line.kak#2]
Selections indicated by `[square brackets]`.

Before any movements:
```
1 |
2 |
3 | [one]
4 | [two]
5 | [three]
6 |
7 |
```

Then moved up once (fine):
```
1 |
2 | [one]
3 | [two]
4 | [three]
5 |
6 |
7 |
```

Then moved down once (broken):
```
1 |
2 | [one]
3 | [two]
4 |
5 | [three]
6 |
7 |
```

Moved down again (broken):
```
1 |
2 | [one]
3 | [two]
4 |
5 |
6 | [three]
7 |
```

All subsequent downward movements will continue to only move the bottom selection.

---

When the whole block is one selection, moving multiple lines is not a problem:
```
1 |
2 |
3 | [one
4 |  two
5 |  three]
6 |
7 |
```
Then moved down once (fine):
```
1 |
2 |
3 |
4 | [one
5 |  two
6 |  three]
7 |
```

**Comment by alexherbo2** [comment]
I stopped working on plugins.

If you have a PR, I’ll happily merge.

**Comment by alexherbo2** [comment]
Fixed.  Revisiting the whole implementation.
