### ISSUE TITLE
Bug when moving selections at the bottom of a buffer

### ISSUE THREAD

**Issue by evanrelf** [alexherbo2/move-line.kak#3]
Selections indicated by `[square brackets]`.

Before any movements:

```
1 | function moveLine() {
2 |   one();
3 |   two()
4 |   three();
5 |[ four();
6 | }]
```

Then moved up once (broken):

```
1 | function moveLine() {
2 |   one();
3 |[ four();
4 | }]
5 |   two()
6 |   three();
```

Then moved down once (fine):

```
1 | function moveLine() {
2 |   one();
3 |   two()
4 |[ four();
5 | }]
6 |   three();
```

Then moved down once (broken):

```
1 | function moveLine() {
2 |   one();
3 |   two()
4 |[ four();
5 | }]
6 |   three();
```

Moving selections that include the last line of the buffer upwards causes them to jump up two lines, and then they can't be moved back to the bottommost line.

**Comment by alexherbo2** [comment]
https://github.com/alexherbo2/move-line.kak/issues/2#issuecomment-541417759

**Comment by alexherbo2** [comment]
Fixed.  Revisiting the whole implementation.
